# Generated by Django 2.0.7 on 2018-07-14 16:59

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(default='', verbose_name='正文')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('clickNums', models.IntegerField(default=0, verbose_name='点击量')),
                ('pic', models.ImageField(default='pic_img/book.jpg', upload_to='pic_img', verbose_name='博客封面图片')),
                ('isShow', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '我的博客',
                'verbose_name_plural': '我的博客',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20, unique=True, verbose_name='类别名字')),
                ('isShow', models.BooleanField(default=True, verbose_name='是否显示')),
                ('lifeOrStudy', models.CharField(choices=[('学无止境', '学无止境'), ('慢生活', '慢生活')], default='学无止境', max_length=10, verbose_name='所属总分类')),
            ],
            options={
                'verbose_name': '文章类别',
                'verbose_name_plural': '文章类别',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=15, unique=True, verbose_name='标签')),
                ('isShow', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='文章类别'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='article.Tag', verbose_name='文章标签'),
        ),
    ]
