# Generated by Django 2.0.7 on 2018-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_userip_visitnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tname',
            field=models.CharField(max_length=30, unique=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='IP地址'),
        ),
    ]
